# Generated by Django 5.1.5 on 2025-01-26 01:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publishTime')),
                ('body', models.TextField()),
                ('publishTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultra_ability_book', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['publishTime'],
                'indexes': [models.Index(fields=['-publishTime'], name='ultra_abili_publish_9ff398_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(default='About Humankind and the World.', max_length=100)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publishTime')),
                ('body', models.TextField()),
                ('publishTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultra_ability_FAQ', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['publishTime'],
                'indexes': [models.Index(fields=['-publishTime'], name='ultra_abili_publish_fb8605_idx')],
            },
        ),
        migrations.CreateModel(
            name='FOTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publishTime')),
                ('body', models.TextField()),
                ('publishTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultra_ability_FOTS', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['publishTime'],
                'indexes': [models.Index(fields=['-publishTime'], name='ultra_abili_publish_a4df6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publishTime')),
                ('body', models.TextField()),
                ('publishTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirleyApp_newsletter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['publishTime'],
                'indexes': [models.Index(fields=['-publishTime'], name='ultra_abili_publish_071bf9_idx')],
            },
        ),
    ]
