# Generated by Django 4.0.6 on 2025-02-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultra_ability', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
