# Generated by Django 4.0.6 on 2025-02-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultra_ability', '0005_rename_created_at_newslettersubscriber_subscribed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersubscriber',
            old_name='subscribed_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='newslettersubscriber',
            old_name='name',
            new_name='full_name',
        ),
    ]
