# Generated by Django 4.0.6 on 2025-02-22 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultra_ability', '0006_rename_subscribed_at_newslettersubscriber_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
