# Generated by Django 4.0.6 on 2025-02-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultra_ability', '0008_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
